package com.tieto.alfresco.gc.monitor.scheduler.exception;

import org.alfresco.error.AlfrescoRuntimeException;

import com.tieto.alfresco.gc.monitor.scheduler.task.ScheduledTask;

/**
 * I18n'ed {@linkplain} AlfrescoRuntimeException thrown by
 * {@link ScheduledRunnerJobImpl} for invalid {@link ScheduledTask}
 * 
 * @author Vitezslav Sliz (vitezslav.sliz@tieto.com)
 */
public class InvalidSchedulerJobException extends AlfrescoRuntimeException {

	private static final long serialVersionUID = -344283087406705547L;
	private static final String ERR_ILEGAL_JOB = "gc.monitor.job.exception.invalid-scheduledJob";

	/**
	 * Construct exception generated by I18n'ed message identified by message ID.
	 * 
	 * @see <b>Message ID:</b> {@value #ERR_ILEGAL_JOB}
	 * 
	 * @param node
	 *            nodeRef
	 */
	public InvalidSchedulerJobException() {
		super(ERR_ILEGAL_JOB, new String[] { ScheduledTask.class.getSimpleName() });
	}
}